version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: high_traffic_db
      POSTGRES_USER: high_traffic_user
      POSTGRES_PASSWORD: high_traffic_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 high_traffic_backend.wsgi:application
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: high_traffic_backend.settings
      DATABASE_URL: postgres://high_traffic_user:high_traffic_password@db:5432/high_traffic_db

volumes:
  postgres_data: